webchat:
  host: 127.0.0.1
  port: 8888
  debug: false
  
  storage:
      entities:
          categories: file
          errors: file
          duplicates: file

          properties: file

          template_nodes: file
          pattern_nodes: file

          preprocessors: file
          postprocessors: file

      stores:

          file:
              type:   file
              config:
                categories_storage:
                  dirs: ../../storage/categories
                  subdirs: true
                  extension: .aiml
                errors_storage:
                  file: ../../storage/debug/errors.txt
                duplicates_storage:
                  file: ../../storage/debug/duplicates.txt

                properties_storage:
                  file: ../../storage/properties/properties.txt

                pattern_nodes_storage:
                  file: ../../../../y-bot/storage/nodes/pattern_nodes.conf
                template_nodes_storage:
                  file: ../../../../y-bot/storage/nodes/template_nodes.conf

                preprocessors_storage:
                  file: ../../storage/processing/preprocessors.conf
                postprocessors_storage:
                  file: ../../storage/processing/postprocessors.conf
  
bot:
    prompt: ">>>"

    initial_question: Hi, how can I help you today?
    default_response: Sorry, I don't have an answer for that!
    default_response_srai: YEMPTY
    empty_string: YEMPTY
    exit_response: So long, and thanks for the fish!
    exit_response_srai: YEXITRESPONSE

    override_properties: true

    max_question_recursion: 1000
    max_question_timeout: 60
    max_search_depth: 100
    max_search_timeout: 60

    conversations:
      type: file
      config_name: file_storage
      empty_on_start: true

    file_storage:
      dir: $BOT_ROOT/conversations

brain:

    # Overrides
    overrides:
      allow_system_aiml: false
      allow_learn_aiml: false
      allow_learnf_aiml: false

    # Defaults
    defaults:
      default-get: unknown
      default-property: unknown
      default-map: unknown

    services:
        PROGRAMY:
            classname: programy.services.programy.ProgramyRESTService
            method: GET
            host: 127.0.0.1
            port: 8989
            url: /api/rest/v1.0/ask
