console:
  description: Program-Y Console Client
  bot:  bot
  prompt: ">>>"

  storage:
      entities:
          categories: file
          errors: file
          duplicates: file
          properties: file
          template_nodes: file
          pattern_nodes: file
          preprocessors: file
          postprocessors: file

      stores:

          file:
              type:   file
              config:
                categories_storage:
                  dirs: ../../storage/categories
                  subdirs: true
                  extension: .aiml
                errors_storage:
                  file: ../../storage/debug/errors.txt
                duplicates_storage:
                  file: ../../storage/debug/duplicates.txt

                properties_storage:
                  file: ../../storage/properties/properties.txt

                pattern_nodes_storage:
                  file: ../../storage/nodes/pattern_nodes.conf
                template_nodes_storage:
                  file: ../../storage/nodes/template_nodes.conf

                preprocessors_storage:
                  file: ../../storage/processing/preprocessors.conf
                postprocessors_storage:
                  file: ../../storage/processing/postprocessors.conf

#####################################################################################################
#

bot:
    brain: brain

    initial_question: Hi, how can I help you today?
    default_response: Sorry, I don't have an answer for that!
    exit_response: So long, and thanks for the fish!

    override_properties: true

    max_question_recursion: 1000
    max_question_timeout: 60
    max_search_depth: 100
    max_search_timeout: 60


#####################################################################################################
#

brain:

    # Overrides
    overrides:
      allow_system_aiml: true
      allow_learn_aiml: true
      allow_learnf_aiml: true

    # Defaults
    defaults:
      default-get: unknown
      default-property: unknown
      default-map: unknown

    # Binary
    binaries:
      save_binary: false
      load_binary: false
      load_aiml_on_binary_fail: false

    debugfiles:
      save-errors: true
      save-duplicates: true

